I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 265, in script
    m "Vector는 {color="#0000000"}크기가 무한대인 배열인데 꽉 차버렸다구요?"
Exception: Open text tag at end of string 'Vector는 {color='.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 265, in script
    m "Vector는 {color="#0000000"}크기가 무한대인 배열인데 꽉 차버렸다구요?"
  File "C:\Users\dswhd\Documents\saksinsiksasasikji\Ren\renpy-8.0.3-sdk\renpy\ast.py", line 921, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\dswhd\Documents\saksinsiksasasikji\Ren\renpy-8.0.3-sdk\renpy\exports.py", line 1373, in say
    who(what, *args, **kwargs)
  File "C:\Users\dswhd\Documents\saksinsiksasasikji\Ren\renpy-8.0.3-sdk\renpy\character.py", line 1266, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "C:\Users\dswhd\Documents\saksinsiksasasikji\Ren\renpy-8.0.3-sdk\renpy\character.py", line 927, in do_display
    display_say(who,
  File "C:\Users\dswhd\Documents\saksinsiksasasikji\Ren\renpy-8.0.3-sdk\renpy\character.py", line 647, in display_say
    what_text.update()
  File "C:\Users\dswhd\Documents\saksinsiksasasikji\Ren\renpy-8.0.3-sdk\renpy\text\text.py", line 1812, in update
    tokens = self.tokenize(text)
  File "C:\Users\dswhd\Documents\saksinsiksasasikji\Ren\renpy-8.0.3-sdk\renpy\text\text.py", line 2280, in tokenize
    tokens.extend(textsupport.tokenize(i))
  File "textsupport.pyx", line 154, in renpy.text.textsupport.tokenize
Exception: Open text tag at end of string 'Vector는 {color='.

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
프로젝트: 벌레캠프! 
Fri Jan 13 23:11:26 2023
